import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    JSON,
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    event,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, Session, mapped_column, relationship

from app.db import Base

JSON_DOCUMENT = JSON().with_variant(JSONB(), "postgresql")


def new_id() -> str:
    return str(uuid.uuid4())


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Household(Base, TimestampMixin):
    __tablename__ = "households"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(120))


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(120))
    username: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False)
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    # Fase 4 (docs/WORK_ORDER_LOCAL_MFA_TOTP.md, "Proteção contra sessão
    # antiga e revogação"): every `ffp_session` cookie embeds the
    # `session_version` it was issued for. `get_current_user` rejects a
    # cookie whose embedded value does not match the current column value
    # -- including a legacy cookie signed before this column existed, which
    # carries no version at all and therefore always fails closed. MFA
    # reconfiguration and the local break-glass CLI reset both revoke every
    # previously issued session by incrementing this column.
    session_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")

    household: Mapped[Household] = relationship()


class MfaFactor(Base, TimestampMixin):
    """One TOTP factor per user (docs/WORK_ORDER_LOCAL_MFA_TOTP.md).

    A single row models both the confirmed, active factor and, while an
    enrollment or reconfiguration is in flight, the *pending* replacement
    factor at the same time -- deliberately, instead of a second table or a
    row-per-attempt history:

    - `secret_encrypted`/`confirmed_at` are the active factor a login
      challenge validates against. Both are `None` until first enrollment
      completes.
    - `pending_secret_encrypted`/`pending_setup_started_at`/
      `pending_setup_expires_at` stage a *new* secret -- generated by
      initial enrollment or by reconfiguration -- without touching the
      active factor. The active factor keeps validating logins throughout
      ("Nunca invalidar o fator antigo antes da confirmação do novo"); only
      confirming the pending code copies it over `secret_encrypted` and
      clears the pending columns.
    - `last_accepted_timestep` guards the *active* `secret_encrypted` --
      shared by every check against it (login challenge, reconfiguration's
      own re-authentication step, recovery-code regeneration's
      re-authentication step): a timestep already accepted for the active
      secret cannot be replayed regardless of which of those flows
      accepted it.
    - `pending_last_accepted_timestep` guards the *pending*
      `pending_secret_encrypted` the same way, independently (enrollment
      confirmation, reconfiguration confirmation). Deliberately a separate
      counter: reconfiguration's re-authentication step (against the still
      -active secret) and its confirmation step (against the new pending
      secret) can legitimately land in the same 30s window -- typing a
      password takes some of that window, but scanning a QR code often
      does not take a full 30s -- and are cryptographically unrelated
      checks. Sharing one counter between them would reject a second,
      entirely legitimate code as a "replay" of the first merely because
      both happened to fall in the same wall-clock timestep.
    - `failed_attempts`/`locked_until` are shared by every TOTP/recovery
      check against this row regardless of which secret: a brute-force
      attempt against any of them consumes the same rate-limit budget.

    Never holds a plaintext secret or a plaintext/recoverable recovery
    code -- see `app.services.mfa` for the encryption and hashing.
    """

    __tablename__ = "mfa_factors"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), unique=True, index=True
    )
    secret_encrypted: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pending_secret_encrypted: Mapped[str | None] = mapped_column(Text, nullable=True)
    pending_setup_started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pending_setup_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_accepted_timestep: Mapped[int | None] = mapped_column(Integer, nullable=True)
    pending_last_accepted_timestep: Mapped[int | None] = mapped_column(Integer, nullable=True)
    failed_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    recovery_codes: Mapped[list["MfaRecoveryCode"]] = relationship(
        back_populates="factor", cascade="all, delete-orphan"
    )


class MfaRecoveryCode(Base):
    """Single-use recovery code verifier (never the plaintext code).

    `code_hash` is an HMAC-SHA256 of the plaintext code keyed by
    `MFA_ENCRYPTION_KEY` (see `app.services.mfa.hash_recovery_code`) --
    one-way, and looked up by direct equality: the code itself already
    carries ~80 bits of random entropy, so no per-row salt is needed to
    resist offline guessing, and the keyed hash still stops anyone with
    read-only database access from using a leaked row without also having
    the application's encryption key.
    """

    __tablename__ = "mfa_recovery_codes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    factor_id: Mapped[str] = mapped_column(ForeignKey("mfa_factors.id", ondelete="CASCADE"), index=True)
    code_hash: Mapped[str] = mapped_column(String(64), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    factor: Mapped[MfaFactor] = relationship(back_populates="recovery_codes")


class Account(Base, TimestampMixin):
    __tablename__ = "accounts"
    __table_args__ = (UniqueConstraint("household_id", "name", name="uq_account_household_name"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(120))
    institution: Mapped[str] = mapped_column(String(80), default="")
    account_type: Mapped[str] = mapped_column(String(30), default="checking")
    owner_label: Mapped[str] = mapped_column(String(80), default="Família")
    last_four: Mapped[str | None] = mapped_column(String(4), nullable=True)
    # FAMILY_FINANCE_CARD_CYCLES_PRIVILEGE_V13
    card_closing_day: Mapped[int | None] = mapped_column(Integer, nullable=True)
    card_due_day: Mapped[int | None] = mapped_column(Integer, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, default=True)


class Category(Base, TimestampMixin):
    __tablename__ = "categories"
    __table_args__ = (UniqueConstraint("household_id", "name", name="uq_category_household_name"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(100))
    color: Mapped[str] = mapped_column(String(7), default="#64748B")
    cash_cap: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    essential: Mapped[bool] = mapped_column(Boolean, default=False)


class Document(Base, TimestampMixin):
    __tablename__ = "documents"
    __table_args__ = (UniqueConstraint("household_id", "sha256", name="uq_document_household_sha"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    account_id: Mapped[str | None] = mapped_column(
        ForeignKey("accounts.id", ondelete="SET NULL"), nullable=True
    )
    original_name: Mapped[str] = mapped_column(String(255))
    document_type: Mapped[str] = mapped_column(String(40))
    sha256: Mapped[str] = mapped_column(String(64), index=True)
    encrypted_path: Mapped[str] = mapped_column(String(500))
    status: Mapped[str] = mapped_column(String(30), default="processing")
    record_count: Mapped[int] = mapped_column(Integer, default=0)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class Transaction(Base, TimestampMixin):
    __tablename__ = "transactions"
    __table_args__ = (
        Index("ix_transaction_household_date", "household_id", "booked_at"),
        Index("ix_transaction_fingerprint", "household_id", "fingerprint"),
        Index("ix_transaction_household_competence", "household_id", "competence"),
        Index("ix_transaction_household_transfer_group", "household_id", "transfer_group_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    account_id: Mapped[str | None] = mapped_column(
        ForeignKey("accounts.id", ondelete="SET NULL"), nullable=True
    )
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    category_id: Mapped[str | None] = mapped_column(
        ForeignKey("categories.id", ondelete="SET NULL"), nullable=True
    )
    booked_at: Mapped[date] = mapped_column(Date)
    description: Mapped[str] = mapped_column(String(500))
    normalized_description: Mapped[str] = mapped_column(String(500), index=True)
    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    transaction_type: Mapped[str] = mapped_column(String(30), default="expense")
    owner_label: Mapped[str] = mapped_column(String(80), default="Família")
    card_last_four: Mapped[str | None] = mapped_column(String(4), nullable=True)
    installment_current: Mapped[int | None] = mapped_column(Integer, nullable=True)
    installment_total: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fingerprint: Mapped[str] = mapped_column(String(64))
    source_line: Mapped[int | None] = mapped_column(Integer, nullable=True)
    occurred_at: Mapped[date | None] = mapped_column(Date, nullable=True)
    competence: Mapped[str | None] = mapped_column(String(7), nullable=True)
    classification_source: Mapped[str] = mapped_column(String(30), default="legacy")
    classification_version: Mapped[str | None] = mapped_column(String(40), nullable=True)
    canonical_status: Mapped[str] = mapped_column(String(24), default="unassigned")
    duplicate_group_id: Mapped[str | None] = mapped_column(
        ForeignKey("duplicate_groups.id", ondelete="SET NULL"), nullable=True, index=True
    )
    linked_transaction_id: Mapped[str | None] = mapped_column(
        ForeignKey("transactions.id", ondelete="SET NULL"), nullable=True
    )
    transfer_group_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    source_priority: Mapped[int] = mapped_column(Integer, default=50)
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4), default=Decimal("1"))
    excluded: Mapped[bool] = mapped_column(Boolean, default=False)
    possible_duplicate: Mapped[bool] = mapped_column(Boolean, default=False)
    reviewed: Mapped[bool] = mapped_column(Boolean, default=False)

    category: Mapped[Category | None] = relationship()
    account: Mapped[Account | None] = relationship()


class ReviewItem(Base, TimestampMixin):
    __tablename__ = "review_items"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    transaction_id: Mapped[str | None] = mapped_column(
        ForeignKey("transactions.id", ondelete="CASCADE"), nullable=True
    )
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=True
    )
    reason: Mapped[str] = mapped_column(String(100))
    details: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="open")
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    transaction: Mapped[Transaction | None] = relationship()


class CaptureDraft(Base, TimestampMixin):
    __tablename__ = "capture_drafts"
    __table_args__ = (
        Index("ix_capture_household_created", "household_id", "created_at"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    user_id: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    source_type: Mapped[str] = mapped_column(String(30))
    detected_type: Mapped[str] = mapped_column(String(40), default="text")
    status: Mapped[str] = mapped_column(String(30), default="preview")
    processor: Mapped[str] = mapped_column(String(60), default="local_rules")
    original_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    extracted_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    proposal_json: Mapped[str] = mapped_column(Text, default="[]")
    result_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4), default=Decimal("0"))
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    document: Mapped[Document | None] = relationship()
    processing_job: Mapped["CaptureProcessingJob | None"] = relationship(
        back_populates="capture_draft", uselist=False
    )


class CaptureProcessingJob(Base, TimestampMixin):
    """Durable, auditable state for asynchronous OCR/audio processing of a
    `CaptureDraft` upload (Fase 3 item 1,
    `docs/WORK_ORDER_ASYNC_OCR_AUDIO_WORKER.md`).

    Moves the potentially slow OCR (scanned image/PDF) and Whisper
    transcription work off the `POST /captures/preview` request path
    without a second OCR/transcription/classification engine, a message
    broker, or any authority over financial facts: this table only ever
    correlates to one `capture_drafts` row and records *when infrastructure
    ran*, never a financial fact -- `app.api._analyze_and_persist_capture`
    remains the single place (shared by the synchronous fast path and this
    worker) that turns processed text into a capture proposal, and human
    confirmation (`POST /captures/{id}/confirm`) remains the only path that
    ever creates a `Transaction`/`Obligation`/`PayrollRecord`.

    One row per `capture_draft_id` (unique): a retry or duplicate delivery
    updates this same row in place (bumping `attempts`) instead of
    inserting a second one, so reprocessing can never fan out into a
    duplicate draft, document or downstream financial record -- see item 4
    ("idempotência em retry"). Claiming
    (`app.services.capture_worker.claim_capture_job`) uses a single atomic
    `UPDATE ... WHERE status = ...` rather than
    `SELECT ... FOR UPDATE SKIP LOCKED` so the exact same claim code is
    race-safe on both PostgreSQL (production) and SQLite (tests) --
    consistent with `docs/INTEGRITY_IMPLEMENTATION_PLAN.md` section 15's
    guidance that heavy async work here should not require Redis.

    `status` lifecycle: `queued` -> `processing` -> `completed` | `failed`.
    A worker crash/timeout leaves a job in `processing`; the crash-recovery
    reconciler (`app/cli/capture_worker.py`) either reclaims it (attempts
    remaining) or explicitly fails it once attempts are exhausted --
    `processing` never silently expires into `completed` (fail-closed, item
    5). `failed` is terminal for automatic reclaim but a household member
    may always retry it explicitly via `POST /captures/{id}/retry`.
    """

    __tablename__ = "capture_processing_jobs"
    __table_args__ = (
        Index("ix_capture_jobs_household_status", "household_id", "status"),
        Index("ix_capture_jobs_status_created", "status", "created_at"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    capture_draft_id: Mapped[str] = mapped_column(
        ForeignKey("capture_drafts.id", ondelete="CASCADE"), unique=True, index=True
    )
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    job_type: Mapped[str] = mapped_column(String(20))
    content_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="queued")
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, default=3)
    claimed_by: Mapped[str | None] = mapped_column(String(80), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(80), nullable=True)
    trace_id: Mapped[str] = mapped_column(String(36), unique=True, index=True, default=new_id)

    capture_draft: Mapped[CaptureDraft] = relationship(back_populates="processing_job")


class Commission(Base, TimestampMixin):
    __tablename__ = "commissions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    description: Mapped[str] = mapped_column(String(200))
    expected_date: Mapped[date] = mapped_column(Date)
    gross_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    tax_rate: Mapped[Decimal] = mapped_column(Numeric(7, 6), default=Decimal("0.06"))
    delay_days: Mapped[int] = mapped_column(Integer, default=60)
    status: Mapped[str] = mapped_column(String(20), default="expected")
    received_date: Mapped[date | None] = mapped_column(Date, nullable=True)


class PayrollRecord(Base, TimestampMixin):
    __tablename__ = "payroll_records"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    person_name: Mapped[str] = mapped_column(String(120))
    competence: Mapped[date] = mapped_column(Date)
    payment_date: Mapped[date] = mapped_column(Date)
    payroll_kind: Mapped[str] = mapped_column(String(30), default="regular")
    gross_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    deductions: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    net_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    payroll_loan: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class Obligation(Base, TimestampMixin):
    __tablename__ = "obligations"

    # FAMILY_FINANCE_OBLIGATION_PAYMENT_V8
    # active=False continua significando cancelada/desativada. O estado de
    # pagamento é separado para que uma obrigação paga continue auditável.
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(200))
    due_date: Mapped[date] = mapped_column(Date)
    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    recurrence_months: Mapped[int] = mapped_column(Integer, default=0)
    occurrence_count: Mapped[int] = mapped_column(Integer, default=1)
    category: Mapped[str] = mapped_column(String(60), default="general")
    status: Mapped[str] = mapped_column(String(20), default="pending")
    paid_at: Mapped[date | None] = mapped_column(Date, nullable=True)
    paid_transaction_id: Mapped[str | None] = mapped_column(
        ForeignKey("transactions.id", ondelete="SET NULL"),
        nullable=True,
        unique=True,
        index=True,
    )
    payment_transaction_created: Mapped[bool] = mapped_column(Boolean, default=False)
    funding_source: Mapped[str] = mapped_column(String(20), default="account")
    funding_transaction_id: Mapped[str | None] = mapped_column(
        ForeignKey("transactions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    funding_balance_observation_id: Mapped[str | None] = mapped_column(
        ForeignKey("account_balance_observations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    active: Mapped[bool] = mapped_column(Boolean, default=True)

    paid_transaction: Mapped[Transaction | None] = relationship(
        foreign_keys=[paid_transaction_id]
    )


class FinancialProfile(Base, TimestampMixin):
    __tablename__ = "financial_profiles"
    __table_args__ = (UniqueConstraint("household_id", name="uq_financial_profile_household"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    monthly_salary_net: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    monthly_cash_cap: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    emergency_floor: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    food_allowance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    meal_allowance_daily: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    workdays_month: Mapped[int] = mapped_column(Integer, default=20)
    investment_name: Mapped[str] = mapped_column(String(120), default="Reserva DI")
    investment_balance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    investment_gross_annual_rate: Mapped[Decimal] = mapped_column(Numeric(9, 8), default=0)
    investment_income_tax_rate: Mapped[Decimal] = mapped_column(Numeric(9, 8), default=0)
    projection_end: Mapped[date | None] = mapped_column(Date, nullable=True)


class AuditEvent(Base):
    __tablename__ = "audit_events"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(ForeignKey("households.id", ondelete="CASCADE"), index=True)
    user_id: Mapped[str | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    event_type: Mapped[str] = mapped_column(String(80))
    entity_type: Mapped[str | None] = mapped_column(String(80), nullable=True)
    entity_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    details: Mapped[str | None] = mapped_column(Text, nullable=True)
    before_state: Mapped[dict[str, Any] | None] = mapped_column(JSON_DOCUMENT, nullable=True)
    after_state: Mapped[dict[str, Any] | None] = mapped_column(JSON_DOCUMENT, nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    source: Mapped[str | None] = mapped_column(String(40), nullable=True)
    request_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )


class IntegrityRun(Base):
    __tablename__ = "integrity_runs"
    __table_args__ = (
        Index("ix_integrity_runs_household_status", "household_id", "status"),
        Index("ix_integrity_runs_household_period", "household_id", "period"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    scope: Mapped[str] = mapped_column(String(20))
    scope_entity_type: Mapped[str | None] = mapped_column(String(80), nullable=True)
    scope_entity_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    period: Mapped[str | None] = mapped_column(String(7), nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="queued")
    trigger: Mapped[str] = mapped_column(String(20))
    financial_rules_version: Mapped[str] = mapped_column(String(20))
    calculation_version: Mapped[str] = mapped_column(String(40))
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    summary: Mapped[dict[str, Any] | None] = mapped_column(JSON_DOCUMENT, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(80), nullable=True)
    trace_id: Mapped[str] = mapped_column(String(36), unique=True, index=True)
    created_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )


class IntegrityFinding(Base, TimestampMixin):
    __tablename__ = "integrity_findings"
    __table_args__ = (
        UniqueConstraint(
            "household_id",
            "fingerprint",
            name="uq_integrity_finding_household_fingerprint",
        ),
        Index("ix_integrity_findings_household_status", "household_id", "status"),
        Index("ix_integrity_findings_household_severity", "household_id", "severity"),
        Index("ix_integrity_findings_household_period", "household_id", "period"),
        Index("ix_integrity_findings_household_invariant", "household_id", "invariant_id"),
        Index("ix_integrity_findings_household_fingerprint", "household_id", "fingerprint"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    run_id: Mapped[str] = mapped_column(
        ForeignKey("integrity_runs.id", ondelete="CASCADE"), index=True
    )
    invariant_id: Mapped[str] = mapped_column(String(12))
    fingerprint: Mapped[str] = mapped_column(String(64))
    financial_rules_version: Mapped[str] = mapped_column(String(20))
    trace_id: Mapped[str] = mapped_column(String(36), index=True)
    source: Mapped[str] = mapped_column(String(24), default="deterministic")
    status: Mapped[str] = mapped_column(String(24), default="open")
    check_status: Mapped[str] = mapped_column(String(16))
    severity: Mapped[str] = mapped_column(String(16))
    scope: Mapped[str] = mapped_column(String(20))
    entity_type: Mapped[str] = mapped_column(String(80))
    entity_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    period: Mapped[str | None] = mapped_column(String(7), nullable=True)
    title: Mapped[str] = mapped_column(String(200))
    message: Mapped[str] = mapped_column(Text)
    expected_amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    actual_amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    difference_amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    expected: Mapped[dict[str, Any] | list[Any] | str | int | float | bool | None] = mapped_column(
        JSON_DOCUMENT, nullable=True
    )
    actual: Mapped[dict[str, Any] | list[Any] | str | int | float | bool | None] = mapped_column(
        JSON_DOCUMENT, nullable=True
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column("metadata", JSON_DOCUMENT, default=dict)
    recommended_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    occurrence_count: Mapped[int] = mapped_column(Integer, default=1)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    acknowledgement_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    resolution_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class DocumentReconciliation(Base):
    __tablename__ = "document_reconciliations"
    __table_args__ = (
        Index(
            "ix_document_reconciliations_household_document",
            "household_id",
            "document_id",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    document_id: Mapped[str] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), index=True
    )
    parser_name: Mapped[str] = mapped_column(String(80))
    parser_version: Mapped[str] = mapped_column(String(40))
    formula_id: Mapped[str] = mapped_column(String(80))
    status: Mapped[str] = mapped_column(String(24))
    period: Mapped[str | None] = mapped_column(String(7), nullable=True)
    declared_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    reconstructed_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    difference: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    opening_balance: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    closing_balance_declared: Mapped[Decimal | None] = mapped_column(
        Numeric(14, 2), nullable=True
    )
    closing_balance_calculated: Mapped[Decimal | None] = mapped_column(
        Numeric(14, 2), nullable=True
    )
    credits_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    debits_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    purchases_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    fees_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    refunds_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    payments_total: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    tolerance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=Decimal("0.01"))
    coverage: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)
    evidence: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)
    reason: Mapped[str | None] = mapped_column(String(120), nullable=True)
    reconciled_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    trace_id: Mapped[str] = mapped_column(String(36), index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class AccountBalanceObservation(Base):
    __tablename__ = "account_balance_observations"
    __table_args__ = (
        Index(
            "ix_account_balance_observations_account_date",
            "household_id",
            "account_id",
            "as_of_date",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    account_id: Mapped[str] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), index=True
    )
    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    as_of_date: Mapped[date] = mapped_column(Date)
    observation_type: Mapped[str] = mapped_column(String(24))
    source: Mapped[str] = mapped_column(String(30))
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    confirmed_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    supersedes_id: Mapped[str | None] = mapped_column(
        ForeignKey("account_balance_observations.id", ondelete="SET NULL"), nullable=True
    )
    superseded_by_id: Mapped[str | None] = mapped_column(
        ForeignKey("account_balance_observations.id", ondelete="SET NULL"), nullable=True
    )
    invalidated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    invalidated_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    invalidation_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_id: Mapped[str] = mapped_column(String(36), index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class DuplicateGroup(Base, TimestampMixin):
    __tablename__ = "duplicate_groups"
    __table_args__ = (
        UniqueConstraint(
            "household_id", "group_key", name="uq_duplicate_group_household_key"
        ),
        Index("ix_duplicate_groups_household_status", "household_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    group_key: Mapped[str] = mapped_column(String(64))
    status: Mapped[str] = mapped_column(String(30), default="open")
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    resolution: Mapped[str | None] = mapped_column(String(40), nullable=True)
    canonical_transaction_id: Mapped[str | None] = mapped_column(
        ForeignKey("transactions.id", ondelete="SET NULL"), nullable=True
    )
    signals: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)
    rule_version: Mapped[str] = mapped_column(String(40))
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    resolution_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class DuplicateGroupMember(Base):
    __tablename__ = "duplicate_group_members"
    __table_args__ = (
        UniqueConstraint(
            "group_id",
            "transaction_id",
            name="uq_duplicate_group_member_transaction",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    group_id: Mapped[str] = mapped_column(
        ForeignKey("duplicate_groups.id", ondelete="CASCADE"), index=True
    )
    transaction_id: Mapped[str] = mapped_column(
        ForeignKey("transactions.id", ondelete="CASCADE"), index=True
    )
    role: Mapped[str] = mapped_column(String(24))
    confidence: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    signals: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)
    source_priority: Mapped[int] = mapped_column(Integer)
    excluded_by_policy: Mapped[bool] = mapped_column(Boolean, default=False)
    added_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class ClassificationRule(Base, TimestampMixin):
    __tablename__ = "classification_rules"
    __table_args__ = (
        UniqueConstraint(
            "household_id",
            "normalized_merchant",
            "category_id",
            "movement_type",
            name="uq_classification_rule_consistent_choice",
        ),
        Index(
            "ix_classification_rules_household_merchant",
            "household_id",
            "normalized_merchant",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    normalized_merchant: Mapped[str] = mapped_column(String(500))
    category_id: Mapped[str] = mapped_column(
        ForeignKey("categories.id", ondelete="CASCADE"), index=True
    )
    movement_type: Mapped[str] = mapped_column(String(30))
    confirmation_count: Mapped[int] = mapped_column(Integer, default=1)
    status: Mapped[str] = mapped_column(String(30), default="observed")
    priority: Mapped[int] = mapped_column(Integer, default=100)
    active: Mapped[bool] = mapped_column(Boolean, default=False)
    created_from_correction: Mapped[bool] = mapped_column(Boolean, default=True)
    last_confirmed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    accepted_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    evidence: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)


class FinancialSnapshot(Base):
    __tablename__ = "financial_snapshots"
    __table_args__ = (
        UniqueConstraint(
            "household_id",
            "period",
            "snapshot_kind",
            "version",
            name="uq_financial_snapshot_version",
        ),
        Index(
            "ix_financial_snapshots_household_period_status",
            "household_id",
            "period",
            "status",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    period: Mapped[str] = mapped_column(String(7))
    snapshot_kind: Mapped[str] = mapped_column(String(20), default="actual")
    version: Mapped[int] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(20), default="current")
    operating_income: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    operating_expenses: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    operating_result: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    bank_cash_in: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    bank_cash_out: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    bank_cash_result: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    investments: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    redemptions: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    internal_transfers: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    card_spend: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    card_payments: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    refunds: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    opening_liquidity_balance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    investment_yield: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    liquidity_used: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    closing_liquidity_balance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    opening_uncovered_deficit: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    closing_uncovered_deficit: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    safety_floor: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    distance_to_floor: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    budget_cap: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    budget_usage: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    budget_remaining: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    commitments: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    projected_balance: Mapped[Decimal] = mapped_column(Numeric(14, 2), default=0)
    source_count: Mapped[int] = mapped_column(Integer, default=0)
    payload: Mapped[dict[str, Any]] = mapped_column(JSON_DOCUMENT, default=dict)
    checksum: Mapped[str] = mapped_column(String(64), index=True)
    calculation_version: Mapped[str] = mapped_column(String(40))
    financial_rules_version: Mapped[str] = mapped_column(String(20))
    integrity_status: Mapped[str] = mapped_column(String(30), default="unknown")
    trusted_for_reports: Mapped[bool] = mapped_column(Boolean, default=False)
    trusted_for_projection: Mapped[bool] = mapped_column(Boolean, default=False)
    superseded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    superseded_by_id: Mapped[str | None] = mapped_column(
        ForeignKey("financial_snapshots.id", ondelete="SET NULL"), nullable=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    generated_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    trace_id: Mapped[str] = mapped_column(String(36), index=True)


class FinancialSnapshotLineage(Base):
    __tablename__ = "financial_snapshot_lineage"
    __table_args__ = (
        Index(
            "ix_financial_snapshot_lineage_metric",
            "snapshot_id",
            "metric_key",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    snapshot_id: Mapped[str] = mapped_column(
        ForeignKey("financial_snapshots.id", ondelete="CASCADE"), index=True
    )
    metric_key: Mapped[str] = mapped_column(String(80))
    entity_type: Mapped[str] = mapped_column(String(80))
    entity_id: Mapped[str] = mapped_column(String(36))
    document_id: Mapped[str | None] = mapped_column(
        ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    rule_id: Mapped[str] = mapped_column(String(80))
    contribution: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    source_role: Mapped[str] = mapped_column(String(24))
    trace_id: Mapped[str] = mapped_column(String(36), index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class MonthlyFinancialClose(Base, TimestampMixin):
    """Human-driven monthly close lifecycle over an already-computed snapshot/run.

    This table never recomputes financial facts: it only records which
    `FinancialSnapshot` and `IntegrityRun` a household reviewed for a period,
    and the human decision (`trusted`) or reversal (`reopened_*`) built on top
    of them. See docs/INTEGRITY_IMPLEMENTATION_PLAN.md section 8.8.

    `financial_revision` (PR 7, Round 8) is the household's
    `HouseholdFinancialRevision.revision` value as of the end of the last
    successful `POST .../run` for this period -- captured under the same
    revision barrier `trust_monthly_close` uses
    (`lock_household_financial_revision`), after `run`'s own
    `IntegrityRun`/`IntegrityFinding` writes. `trust_monthly_close` requires
    this to still equal the barrier's current value before accepting
    `trusted`: comparing `close.snapshot_id` to a freshly rebuilt snapshot
    alone (the Round 6 fix) only detects a mutation that changed *this
    period's* recomputed snapshot. A mutation to a source `run` also
    depends on but that does not change this period's snapshot -- e.g.
    editing `installment_total` on a transaction booked in an *earlier*
    period, which changes `_future_installments()`'s next-month projection
    without touching the closed period's own snapshot -- would otherwise
    leave both the snapshot identity check and the old run's stored
    `healthy` status silently satisfied. See the engineering review on PR 7,
    Round 8: "Persist the revision used by /run on the close/run and
    require it to equal the locked revision before trusting."　Nullable:
    a close created before this column existed (every pre-migration
    `review_required` row -- migration `0008` is additive and does not
    backfill) or one manufactured directly by a test that bypasses the real
    `run` endpoint has no recorded value. Since the Round 10 fix,
    `trust_monthly_close` treats `None` as missing evidence and fails closed
    -- any *new* promotion from `review_required` requires a real `run` to
    capture a revision first; it is not treated as "not applicable". A close
    already sitting at `trusted` (created under the earlier, more permissive
    behavior) is never retroactively invalidated by this: `trust_monthly_close`
    only ever evaluates this column while promoting a `review_required`
    close, never against an already-`trusted` one. See the engineering
    review on PR 7, Round 10: "Unknown provenance must fail closed... a NULL
    revision should add a gate reason requiring a fresh /run, not mean 'not
    applicable'."
    """

    __tablename__ = "monthly_financial_closes"
    __table_args__ = (
        UniqueConstraint(
            "household_id", "period", name="uq_monthly_financial_close_household_period"
        ),
        Index("ix_monthly_financial_closes_household_status", "household_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), index=True
    )
    period: Mapped[str] = mapped_column(String(7), index=True)
    status: Mapped[str] = mapped_column(String(20), default="open", index=True)
    snapshot_id: Mapped[str | None] = mapped_column(
        ForeignKey("financial_snapshots.id", ondelete="SET NULL"), nullable=True, index=True
    )
    integrity_run_id: Mapped[str | None] = mapped_column(
        ForeignKey("integrity_runs.id", ondelete="SET NULL"), nullable=True, index=True
    )
    financial_revision: Mapped[int | None] = mapped_column(Integer, nullable=True)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    reopened_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    reopened_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class HouseholdFinancialRevision(Base):
    """Monotonic per-household revision counter, bumped inside the *same*
    transaction as every mutation to a Financial-Engine input (see the
    event listener below).

    `run_monthly_close`, `trust_monthly_close` and `reopen_monthly_close`
    (`app/services/monthly_close.py`, `app/api.py`; helpers in
    `app/services/financial_revision.py`) all read/lock this row, as their
    very first action, to close two distinct windows:

    1. The TOCTOU window between recomputing a period's canonical
       `FinancialSnapshot` and committing `trusted` -- see the engineering
       review on PR 7, Round 7: "The trust transition must be serialized
       with every financial source mutation that can affect the snapshot
       ... or use a monotonic source revision validated inside the same
       transactional barrier. The production guarantee must be real on
       PostgreSQL; SQLite may use a deterministic test-equivalent path but
       must not be presented as equivalent locking semantics."
    2. The race between the monthly close lifecycle's own transitions --
       `run`, `trust` and `reopen` concurrently acting on the same
       (household, period) close -- see the engineering review on PR 7,
       Round 11: taking this same row as the first action of all three,
       before any of them reads `close.status`, means whichever gets here
       first for a household fully completes its own transition (state
       check through final write and commit) before either of the other
       two can even read that status. Before this fix, `run_monthly_close`
       read `close.status` *before* acquiring this lock; a `trust` that
       committed in that window was invisible to it, and the run's own
       unconditional final write silently downgraded a just-`trusted`
       close back to `review_required` with no `reopen` reason, no
       `reopened_by` and no audit trail for the demotion.

    On PostgreSQL, `SELECT ... FOR UPDATE` against this row
    (`lock_household_financial_revision`) takes the same row-level write
    lock the upsert below takes, blocking any concurrent mutation's own
    bump of the same row -- and any concurrent `run`/`trust`/`reopen` on
    the same household's monthly closes -- until the lock-holding
    transaction commits or rolls back. SQLite (tests) has no real
    cross-connection row lock; there, `trust_monthly_close` still compares
    the revision value read at the start of the transaction against the
    value read again right before the `trusted` write, inside the same
    transaction, and `assert_close_runnable`/`upsert_monthly_close_after_run`
    re-validate `close.status` immediately before each final write -- a
    deterministic, testable stand-in for the guarantees the PostgreSQL lock
    provides unconditionally.
    """

    __tablename__ = "household_financial_revisions"

    household_id: Mapped[str] = mapped_column(
        ForeignKey("households.id", ondelete="CASCADE"), primary_key=True
    )
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class BackfillRun(Base):
    """Auditable manifest row for one invocation of `app.cli.backfill`.

    Deliberately its own table, not another `IntegrityRun` (`trigger="backfill"`
    already exists on that model and is still used per-household/per-period by
    `execute_integrity_run` during a backfill): a single `app.cli.backfill`
    invocation can span every household and many periods, and PR 8's Work
    Order requires recording "run, versões, duração, resultado e
    rastreabilidade suficiente para auditoria" for the *backfill process
    itself*, independent of however many `IntegrityRun`/`FinancialSnapshot`/
    `DocumentReconciliation`/`DuplicateGroup` rows it touches underneath.

    Not listed in `FINANCIAL_REVISION_MODELS` below: this row never feeds
    `financial_snapshots._collect()` or a monthly-close trust gate the way an
    `IntegrityRun`/`IntegrityFinding` row does -- it is a record *about* a
    process, like `AuditEvent` (also absent from that list), not a financial
    fact or gate input a snapshot recomputation could diverge from.

    `dry_run=True` rows are written *after* the in-memory pass completes and
    the session that ran it is rolled back (see `app/cli/backfill.py`): the
    manifest of what a dry run *would* have done is itself audit-worthy
    evidence, and is committed on its own, separate connection/transaction so
    it survives the rollback of every other change the dry run touched.
    """

    __tablename__ = "backfill_runs"
    __table_args__ = (Index("ix_backfill_runs_status", "status"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    status: Mapped[str] = mapped_column(String(20), default="running")
    dry_run: Mapped[bool] = mapped_column(Boolean, default=False)
    household_scope: Mapped[dict[str, Any] | None] = mapped_column(JSON_DOCUMENT, nullable=True)
    period_from: Mapped[str | None] = mapped_column(String(7), nullable=True)
    period_to: Mapped[str | None] = mapped_column(String(7), nullable=True)
    financial_rules_version: Mapped[str] = mapped_column(String(20))
    calculation_version: Mapped[str] = mapped_column(String(40))
    app_version: Mapped[str | None] = mapped_column(String(40), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    summary: Mapped[dict[str, Any] | None] = mapped_column(JSON_DOCUMENT, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(80), nullable=True)
    trace_id: Mapped[str] = mapped_column(String(36), unique=True, index=True)
    triggered_by: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )


# Every model whose rows feed either (a) `app/services/financial_snapshots.py`'s
# `_collect()` (what a period's `FinancialSnapshot` recomputes to) or (b) a
# deterministic gate `trust_monthly_close` relies on without recomputing --
# `consolidated_integrity_status()` (reads `IntegrityRun`/`IntegrityFinding`)
# and `_build_projection_gate_checks()`/INV-018 (reads `Commission`/
# `PayrollRecord` for the projection's commission/extra-payroll inputs). A
# mutation to any of these can change what the period's snapshot or its
# integrity/projection gates would recompute to, so each one must bump
# `HouseholdFinancialRevision`. Kept next to the model (not buried in
# `app/services/financial_revision.py`) so adding a new snapshot-input or
# gate-input model elsewhere in this file is a one-line, code-reviewable
# decision about whether it belongs here, not a separate cross-module wiring
# step easy to forget -- see the engineering review on PR 7, Round 7 ("source
# mutation endpoints do not share the snapshot advisory lock") and Round 8
# ("Fresh evidence in the Round 8 barrier is that this model list omits
# IntegrityRun and IntegrityFinding ... and also omits Commission and
# PayrollRecord").
FINANCIAL_REVISION_MODELS: tuple[type, ...] = (
    Transaction,
    Account,
    AccountBalanceObservation,
    Obligation,
    FinancialProfile,
    DocumentReconciliation,
    Category,
    Document,
    Commission,
    PayrollRecord,
    IntegrityRun,
    IntegrityFinding,
)


@event.listens_for(Session, "before_flush")
def _bump_financial_revision_on_source_mutation(session: Session, flush_context, instances) -> None:
    """Bump `HouseholdFinancialRevision` for every household touched by this
    flush's new/dirty/deleted `FINANCIAL_REVISION_MODELS` rows, inside the
    same flush -- see `HouseholdFinancialRevision`'s docstring.

    A `Session`-level hook, not a bump call added by hand to each mutating
    endpoint: an endpoint written later that touches any
    `FINANCIAL_REVISION_MODELS` row is covered automatically instead of
    depending on every future author remembering to call one, which is
    exactly the kind of gap the engineering review on PR 7, Round 7 found.

    Imports `bump_household_financial_revision` locally to avoid a circular
    import (`app.services.financial_revision` imports
    `HouseholdFinancialRevision` from this module); by the time a flush can
    happen, both modules are already fully loaded.
    """

    del flush_context, instances
    from app.services.financial_revision import bump_household_financial_revision

    household_ids: set[str] = set()
    for obj in (*session.new, *session.dirty, *session.deleted):
        if isinstance(obj, FINANCIAL_REVISION_MODELS):
            household_id = getattr(obj, "household_id", None)
            if household_id:
                household_ids.add(household_id)
    for household_id in household_ids:
        bump_household_financial_revision(session, household_id=household_id)
